Good to go, Xioa, Wisblock, LoRa CLI, TERM, RTT

diff --git a/assets/MemFault/cpMemfltSrcFiles b/assets/MemFault/cpMemfltSrcFiles
--- a/assets/MemFault/cpMemfltSrcFiles
+++ b/assets/MemFault/cpMemfltSrcFiles
@@ -272,31 +272,13 @@ function fixAdafruitFiles()
   mkdir -p $PIO_PROJDIR/include/drivers/
   cp $PIO_FRAMEWORK_ARDUINO_ADA/cores/nRF5/nordic/nrfx/drivers/nrfx_common.h $PIO_PROJDIR/include/drivers
 
-  # default Adafruit main.cpp file
-  fgrep nrf_drv_clock_init  $PIO_FRAMEWORK_ARDUINO_ADA/cores/nRF5/main.cpp > /dev/null
-  if [ $? -eq 0 ]
-  then
-  	echo ""
-  else
-       echo "Error: "
-       echo "    The PlatformIO Adafruit file, cores/nRF5/main.cpp, needs to be updated."
-       echo ""
-       echo "    A sample replacement file can be found within this project at:"
-       echo "    assets/MemFault/AdaFruitFramework/framework-arduinoadafruitnrf52/cores/nRF5/main.cpp"
-       echo ""
-       echo "    Merge the changes contained with this file, look for instances of \"#ifdef MEMFAULT\""
-       echo "    Location of file to be updated:"
-       echo "$PIO_FRAMEWORK_ARDUINO_ADA/cores/nRF5/main.cpp"
-       echo ""
-  fi
 
 }
 
-# Update customized memfault files
+# Update customized Memfault files
 # 
 function fixMemfaultFiles()
 {
-# customize Memfault source files
   mkdir -p $PIO_PROJLIB/$PIO_MEMFLT_LIBDIR/ports/freertos/src/
   cp $ASSET_DIR/MemfaultSrc/lib/memfault/ports/freertos/src/memfault_freertos_ram_regions.c $PIO_PROJLIB/$PIO_MEMFLT_LIBDIR/ports/freertos/src/
   mkdir -p  $PIO_PROJLIB/$PIO_MEMFLT_LIBDIR/components/core/src/
@@ -304,12 +286,13 @@ function fixMemfaultFiles()
 
 }
 
-# Update the Adafruit Tiny USB library.json file,  
+# Update the Adafruit library "library.json" file,  
 # required to remove "nrf5_sdk" include file collisions when
 # compiling Adafruit files
 #
-function checkForTinyUSBFixes
+function checkForLibraryExtraScripts()
 {
+  // TinyUSB
   LIB_JSON=~/.platformio/packages/framework-arduinoadafruitnrf52/libraries/Adafruit_TinyUSB_Arduino/library.json
 
   fgrep '"extraScript"' $LIB_JSON > /dev/null
@@ -327,12 +310,30 @@ function checkForTinyUSBFixes
        echo "    assets/MemFault/AdaFruitFramework/framework-arduinoadafruitnrf52/libraries/Adafruit_TinyUSB_Arduino"
   fi
 
+
+  // SPI
+  LIB_SPIJSON=~/.platformio/packages/framework-arduinoadafruitnrf52/libraries/SPI/library.json
+
+  fgrep '"extraScript"' $LIB_SPIJSON > /dev/null
+
+  if [ $? -eq 0 ]
+  then
+       #echo "OK: Found updated files"
+       echo ""
+  else
+       echo "Error: "
+       echo "    The PlatformIO Adafruit SPI library.json must contain an "extraScrip" entry."
+       echo "    File: $LIB_SPIJSON"
+       echo ""
+       echo "    Replacement files can be found within the project at:"
+       echo "    assets/MemFault/AdaFruitFramework/framework-arduinoadafruitnrf52/libraries/SPI"
+  fi
 }
 
- copyFiles
+copyFiles
 fixAdafruitFiles
 fixMemfaultFiles
-checkForTinyUSBFixes
+checkForLibraryExtraScripts
 
 #rmFiles
 rm -f $srcFiles
